### ISSUE TITLE
socket超时处理

### ISSUE THREAD

**Issue by changruisun** [tinylcy/vino#3]
如果一个socket连接注册到epoll了，发送http报文发送的不完整，客户端又不关闭，也不继续发送数据，这种链接server端，如何做超时关闭处理

**Comment by tinylcy** [comment]
谢谢你提出这个issue，对于你说的情况，需要设计和实现timer来解决超时事件。回到具体应用，可以参考Tengine的[设计](http://tengine.taobao.org/download/programmer-201209-Tengine.pdf)，利用最小堆来实现timer，这也是tinyhttpd目前存在的问题之一，我将会在后续进行完善 :-)

**Comment by tinylcy** [comment]
已对代码进行重构，增加socket超时处理。
