### ISSUE TITLE
通读了一遍代码，发现您未完整实现Reactor模式

### ISSUE THREAD

**Issue by summychou** [tinylcy/vino#6]
代码中的工作模式是单EPOLL线程+单工作线程，是否考虑加入工作线程池。

**Comment by tinylcy** [comment]
你好，是否加入线程池，我觉得要看具体的场景，nginx 引入线程池的目的是防止某些耗时比较长的操作延误事件循环，假设我们的场景不会涉及耗时很长的操作，那么单线程就够用了。如果瓶颈是磁盘 I/O，那么引入多线程应该可以提高性能，当然多线程还会带来线程调度的开销以及锁竞争的开销，这个需要权衡。

有时间的话，应该会去实现一下线程池 :D。

你提交的 pull/requests 我看到了，很高兴你有时间阅读我的代码，不过你阅读的可能不是最新的（今天增加了一个有限状态自动机，用于实现 HTTP Parser）。

**Comment by summychou** [comment]
了解！！！通读一遍，你的代码结果很适合我的胃口！！！我会持续关注更新的！！！

**Comment by tinylcy** [comment]
@summychou 有 bug | 设计不合理之处 | 建议，也欢迎讨论。
